---
# defaults file for calico-node
csr:
  C: ID
  L: Jakarta
  O: Kubernetes
  OU: Kubernetes Cluster 01
  ST: Jakarta Selatan

generate_tls: false
tls_ca_config: ca-config.json
tls_ca: ca.pem
tls_ca_key: ca-key.pem
tls_cert: calico.pem
tls_key: calico-key.pem

calico_bootstrap: false
calico_basedir: /etc/calico
calico_certdir: /etc/calico/certs
calico_version: v3.5.5
calico_asn: 64567
calico_ippool_name: "mypool"
calico_ipip_mode: Always
calico_peer_ip: "{{ ansible_default_ipv4.gateway }}"

etcd_tls_enabled: false
etcd_endpoints: "https://localhost:2379"
