
- name: Generating kubeconfig
  args:
    chdir: "{{ kube_homedir }}/config"
    creates: "{{ kube_homedir }}/config/{{ item.unit }}.kubeconfig"
  shell: |
    {{ kube_homedir }}/bin/kubectl config set-cluster kubernetes \
    --certificate-authority={{ kube_homedir }}/certs/ca.pem \
    --server=https://{{ kube_apiserver_external_address }}:6443 \
    --embed-certs=true \
    --kubeconfig={{ item.unit }}.kubeconfig && \

    {{ kube_homedir }}/bin/kubectl config set-credentials {{ item.credential }} \
    --client-certificate={{ kube_homedir }}/certs/{{ item.unit }}.pem \
    --client-key={{ kube_homedir }}/certs/{{ item.unit }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ item.unit }}.kubeconfig && \

    {{ kube_homedir }}/bin/kubectl config set-context default \
    --cluster=kubernetes \
    --user={{ item.credential }} \
    --kubeconfig={{ item.unit }}.kubeconfig && \

    {{ kube_homedir }}/bin/kubectl config use-context default --kubeconfig={{ item.unit }}.kubeconfig

  with_items:
  - { unit: "kubelet",    credential: "system:node:{{ ansible_default_ipv4.address }}"}
  - { unit: "kube-proxy", credential: "system:kube-proxy"}
