---
# tasks file for kube-worker

- name: Create kubernetes directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ kube_homedir }}"
    - "{{ kube_homedir }}/bin"
    - "{{ kube_homedir }}/certs"
    - "{{ kube_homedir }}/config"
    - "{{ kube_homedir }}/cni/net.d"
    - "{{ kube_homedir }}/cni/bin"
  tags:
    - install

- include: install.yml
  tags:
    - install

- include: tweaking.yml
- include: disable_swap.yml

- include: generate_certs.yml
  tags:
    - tls

- include: generate_kubeconfig.yml
  tags:
    - kubeconfig

- include: setup_cri.yml
  tags:
    - setup

- include: setup_cni.yml
  tags:
    - setup

- include: setup.yml
  tags:
    - setup

- include: smoke_test.yml
