- name: tweak sysctl kernel.pid_max
  sysctl:
    name: kernel.pid_max
    value: 4194303
    sysctl_set: yes
  tags:
    - sysctl

- name: tweak sysctl vm.swappiness
  sysctl:
    name: vm.swappiness
    value: 0
    sysctl_set: yes
  tags:
    - sysctl

- name: tweak sysctl kernel net.ipv4.ip_local_port_range
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "40000 64000"
    sysctl_set: yes
  tags:
    - sysctl
    - dependency
