---
# tasks file for certificates

- name: Download cfssl & cfssljson
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0655'
  with_items:
  - { url: "https://pkg.cfssl.org/R1.2/cfssl_darwin-amd64",     dest: "/usr/bin/cfssl"}
  - { url: "https://pkg.cfssl.org/R1.2/cfssljson_darwin-amd64", dest: "/usr/bin/cfssljson" }

- name: Generate certificates
  shell: |
   /usr/bin/cfssl gencert \
   -ca={{ tls_ca }} \
   -ca-key={{ tls_ca_key }} \
   -config={{ tls_ca_config }} \
   -profile=kubernetes \
   {{ unit }}-csr.json | cfssljson -bare {{ unit }}
