
- name: Generating kubeconfig
  args:
    chdir: "{{ item.dir }}"
    creates: "{{ item.dest }}"
  shell: |
    /usr/local/bin/kubectl config set-cluster kubernetes \
    --certificate-authority={{ kube_homedir }}/certs/ca.pem \
    --server=https://{{ kube_apiserver_external_address }}:6443 \
    --embed-certs=true \
    --kubeconfig={{ item.dest }} && \

    /usr/local/bin/kubectl config set-credentials {{ item.credential }} \
    --client-certificate={{ kube_homedir }}/certs/{{ item.unit }}.pem \
    --client-key={{ kube_homedir }}/certs/{{ item.unit }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ item.dest }} && \

    /usr/local/bin/kubectl config set-context default \
    --cluster=kubernetes \
    --user={{ item.credential }} \
    --kubeconfig={{ item.dest }} && \

    /usr/local/bin/kubectl config use-context default --kubeconfig={{ item.dest }}

  with_items:
  - { dir: "{{ kube_homedir }}/kubelet", unit: "kubelet",    credential: "system:node:{{ ansible_hostname }}", dest: "{{ kube_homedir }}/kubelet/kubeconfig"}
  - { dir: "{{ kube_homedir }}/kube-proxy", unit: "kube-proxy", credential: "system:kube-proxy",              dest: "{{ kube_homedir }}/kube-proxy/kubeconfig"}
