---
- name: Install Erlang from Bintray
  yum:
    name: https://bintray.com/rabbitmq-erlang/rpm/download_file?file_path=erlang%2F21%2Fel%2F7%2Fx86_64%2Ferlang-21.2.6-1.el7.x86_64.rpm
    state: present

- name: Install socat & logrotate
  yum:
    name:
      - socat
      - logrotate
    state: present

- name: Install RabbitMQ from Bintray
  yum:
    name: https://bintray.com/rabbitmq/rpm/download_file?file_path=rabbitmq-server%2Fv3.7.x%2Fel%2F7%2Fnoarch%2Frabbitmq-server-3.7.12-1.el7.noarch.rpm
    state: present
