- name: Setup kubernetes service IP
  shell: "ipcalc {{ kube_service_cluster_ip_range }} | awk '/HostMin/ {print $2}'"
  register: kube_service_ip

- name: Copying Certificate Authority
  copy:
    src: "{{ item }}"
    dest: "{{ kube_homedir }}/certs"
  with_items:
  - "{{ tls_ca }}"
  - "{{ tls_ca_key }}"
  - "{{ tls_ca_config }}"

- name: Generate CSR
  template:
    src: "csr/{{ item }}-csr.json.j2"
    dest: "{{ kube_homedir }}/certs/{{ item }}-csr.json"
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kube-proxy
  - service-account
  - admin

- name: Generating kubernetes master certificates
  args:
    chdir: "{{ kube_homedir }}/certs"
    creates: "{{ kube_homedir }}/certs/{{ item }}.pem"
  shell: |
   /usr/bin/cfssl gencert  \
   -ca={{ tls_ca }} \
   -ca-key={{ tls_ca_key }} \
   -config={{ tls_ca_config }} \
   -profile=kubernetes \
   {{ item }}-csr.json | /usr/bin/cfssljson -bare {{ item }}
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kube-proxy
  - service-account
  - admin
