- name: Copying Certificate Authority
  copy:
    src: "{{ item }}"
    dest: "{{ etcd_basedir }}/certs/"
  with_items:
  - "{{tls_ca}}"
  - "{{tls_ca_key}}"
  - "{{tls_ca_config}}"

- name: Generate CSR
  template:
    src: "etcd-csr.json.j2"
    dest: "{{ etcd_basedir }}/certs/etcd-csr.json"

- name: Generating etcd certificates
  args:
    chdir: "{{ etcd_basedir }}/certs"
    creates: "{{ etcd_basedir }}/certs/etcd.pem"
  shell: |
   /usr/bin/cfssl gencert  \
   -ca={{tls_ca}} \
   -ca-key={{tls_ca_key}} \
   -config={{tls_ca_config}} \
   -profile=kubernetes \
   etcd-csr.json | /usr/bin/cfssljson -bare etcd
