---
# tasks file for kube-etcd

- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ etcd_basedir }}"
    - "{{ etcd_basedir }}/certs"
    - "{{ etcd_datadir }}"

- include: install.yml
- include: generate_certs.yml
  when: etcd_tls_enabled

- include: setup.yml
- include: smoke_test.yml
  when: not etcd_proxy
