- name: Ensure etcd package directory exist
  file:
    path: /tmp/etcd
    state: directory

- name: Extract etcd package
  unarchive:
    remote_src: yes
    src: "/tmp/etcd.tar.gz"
    dest: "/tmp/etcd"
    extra_opts: [--strip-components=1]

- name: Move etcd binaries
  copy:
    remote_src: yes
    src: "/tmp/etcd/{{ item }}"
    dest: /usr/local/bin/
    mode: '0655'
  with_items:
  - etcd
  - etcdctl

- name: Create systemd unit
  template:
    src: "etcd.service.j2"
    dest: "/etc/systemd/system/etcd.service"
  when: not etcd_proxy

- name: Started etcd service
  systemd:
    name: etcd
    enabled: yes
    state: started
    daemon_reload: yes
  when: not etcd_proxy

- name: Create systemd unit (proxy)
  template:
    src: "etcd-proxy.service.j2"
    dest: "/etc/systemd/system/etcd-proxy.service"
  when: etcd_proxy

- name: Started etcd-proxy service
  systemd:
    name: etcd-proxy
    enabled: yes
    state: started
    daemon_reload: yes
  when: etcd_proxy

- name: Remove unnecessary package
  shell: "rm -rf {{ item }}"
  with_items:
  - "/tmp/etcd*"
#   - "/usr/bin/cfssl"
#   - "/usr/bin/cfssljson"
