
- name: Readiness check
  shell: |
   ETCDCTL_API=3 etcdctl member list \
    {% if etcd_tls_enabled %}
    --endpoints=https://127.0.0.1:2379 \
    --cacert={{ etcd_basedir }}/certs/{{ tls_ca }} \
    --cert={{ etcd_basedir }}/certs/{{ tls_cert }} \
    --key={{ etcd_basedir }}/certs/{{ tls_key }}
    {% endif %}
  register: readiness
