
- name: Generating kubeconfig
  args:
    chdir: "{{ kube_homedir }}/config"
    creates: "{{ kube_homedir }}/{{ item.unit }}.kubeconfig"
  shell: |
    {{ kube_homedir }}/bin/kubectl config set-cluster kubernetes \
    --certificate-authority={{ kube_homedir }}/certs/ca.pem \
    --server=https://127.0.0.1:6443 \
    --embed-certs=true \
    --kubeconfig={{ item.unit }}.kubeconfig && \

    {{ kube_homedir }}/bin/kubectl config set-credentials {{ item.credential }} \
    --client-certificate={{ kube_homedir }}/certs/{{ item.unit }}.pem \
    --client-key={{ kube_homedir }}/certs/{{ item.unit }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ item.unit }}.kubeconfig && \

    {{ kube_homedir }}/bin/kubectl config set-context default \
    --cluster=kubernetes \
    --user={{ item.credential }} \
    --kubeconfig={{ item.unit }}.kubeconfig && \

    {{ kube_homedir }}/bin/kubectl config use-context default --kubeconfig={{ item.unit }}.kubeconfig

  with_items:
  - { unit: "kube-controller-manager",  credential: "system:kube-controller-manager"}
  - { unit: "kube-scheduler",           credential: "system:kube-scheduler"}
  - { unit: "admin",                    credential: "admin"}
