---
- name: Download cfssl & cfssljson
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0655'
  with_items:
  - { url: "https://pkg.cfssl.org/R1.2/cfssl_linux-amd64",     dest: "/usr/bin/cfssl"}
  - { url: "https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64", dest: "/usr/bin/cfssljson" }

- name: Download kubernetes binaries
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kube_version }}/bin/linux/amd64/{{ item.unit }}"
    dest: "{{ item.dest }}"
    mode: '0655'
  with_items:
  - { unit: "kube-apiserver", dest: "{{ kube_homedir }}/bin" }
  - { unit: "kube-controller-manager", dest: "{{ kube_homedir }}/bin"}
  - { unit: "kube-scheduler", dest: "{{ kube_homedir }}/bin"}
  - { unit: "kubectl", dest: "/usr/local/bin"}

- name: Download kubernetes master dependencies
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
        - ipcalc
