# https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#JoinConfiguration
# https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#NodeRegistrationOptions
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  name: "kube-worker-0"
  criSocket: "/var/run/dockershim.sock"
  taints:
  - key: "node-role"
    value: "worker"
    effect: "NoSchedule"
  kubeletExtraArgs:
    cgroup-driver: "cgroupfs"
discovery:
  bootstrapToken:
    token: 783bde.3f89s0fje9f38fhf
    apiServerEndpoint: k8s.projects.ardika.io:6443
    caCertHashes:
    - sha256:15d8e86100fdbca627ce702b30b85d3764ef9f012c43fb7d20c1687c3bad050d
  timeout: 3m
