---
- name: Ensure swarm exist
  command: "docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}"
  failed_when: false
  ignore_errors: yes
  when: swarm_bootstrap

- name: Get manager token
  command: "docker swarm join-token manager -q"
  register: manager_token
  tags:
    - setup
    - token

- name: Get worker token
  command: "docker swarm join-token worker -q"
  register: worker_token
  tags:
    - setup
    - token

- name: Register swarm token
  set_fact:
    manager_address: "{{ ansible_default_ipv4.address }}"
    manager_token: "{{ manager_token.stdout }}"
    worker_token: "{{ worker_token.stdout }}"
