---

- name: Join manager
  command: "docker swarm join --token {{ manager_token }} {{ manager_address }}:2377"
  ignore_errors: yes"
  when:
    - inventory_hostname != ( swarm_managers | first )
    - inventory_hostname in swarm_managers

- name: Join worker
  command: "docker swarm join --token {{ worker_token }} {{ manager_address }}:2377"
  ignore_errors: yes
  when:
    - inventory_hostname in swarm_workers
