---
# tasks file for kube-etcd

- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ calico_basedir }}"
    - "{{ calico_basedir }}/certs"
    - "{{ calico_basedir }}/conf"

- include: install.yml
- include: generate_certs.yml
  when: generate_tls
- include: setup.yml
